version: '3.1'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGODB_DATABASE: nest-pokemon

volumes:
  mongodb_data:
    driver: local
